### ISSUE TITLE
Add NOAA's radar.weather.gov

### ISSUE THREAD

**Issue by caffeinejolt** [noremacsim/fossa-vue#1]
This can come in handy while on the road and making decisions based on weather.

https://radar.weather.gov/

**Comment by noremacsim** [comment]
Users have the ability to add any custom Link to there homepage by clicking the **Plus Tile** and selecting **Add New URL.**

Alternatively They can also select from a list of predefined Apps by selecting **Add New App**

I have created a PR and added this into the default app list.
